[package]
name = "threegis-core-wasm"
version = "0.1.0"
edition = "2021"
description = "WebAssembly core implementation for threegis geometry processing"
authors = [""]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
web-sys = { version = "0.3.64", features = ["console"] }
geojson = "0.24.1"
geo = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
opt-level = 3
lto = true
